plugins {
    id 'com.android.application'
}

android {
    namespace 'com.erp.injector'
    compileSdk 34

    defaultConfig {
        applicationId "com.erp.injector"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    // Автоматичне перейменування збірки в Exp2.apk
    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "Exp2.apk"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
