apply plugin: 'com.android.application'

android {
    namespace 'com.ezp.injector'
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.ezp.injector"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
